### PR TITLE
Updated Auth to use basic authentication

### PR DESCRIPTION
**Pull request by drathm**
Master appears to be broken by mixpanel now with the depreciation. I'm using @robin900 auth branch and fixed a small import and auth string bug

### CODE REVIEW

**Comment by cooncesean** [comment]
@drathm can you provide a link to what Mixpanel changed w/ regards to their API?

@thesmallestduck we are currently using this in production; have we noticed any errors lately with regards to fetching data from Mixpanel using the existing version of master of this lib?

**Comment by drathm** [comment]
I can't find any reference to changes, but here is the auth documentation which refers to basic auth. My client was returning a 400 before applying @robin900 change.

https://mixpanel.com/help/reference/jql/api-reference#api/access

**Comment by robin900** [comment]
@drathm I wonder: if you change `Connection.ENDPOINT` to be `'https://mixpanel.com/api'`, will the use of HTTPS will cause the old authentication approach to be successful, without these changes?

I still support switching to use the new basic auth scheme exclusively, since it works against all endpoints and isn't subject to future deprecation.

**Comment by thesmallestduck** [comment]
I am not against using the documented authentication method, despite it feeling like a step backwards to me. I will note we currently use master on our production deployment and are not having trouble with our authed calls. I suppose it is possible our project has been grandfathered into old auth methods while new projects are not supported. The last time we discussed this mixpanel stated they had no plans to deprecate the old method of authentication.

Maybe @jaredmixpanel can weigh in again, and these plans have changed?

**Comment by thesmallestduck** [comment]
Or perhaps it is their new JQL product feature that does not support the old auth method, we use the segmentation API predominantly.

**Comment by jaredmixpanel** [comment]
@thesmallestduck to my knowledge nothing has changed since we last discussed this. but feel free to write into support@mixpanel.com with the details of the failing API calls and we can take a closer look.

**Comment by thesmallestduck** [comment]
@drathm I've attempted to add support for this means of authentication (while maintaining signature-based authentication) here: https://github.com/cooncesean/mixpanel-query-py/issues/30

When you get a chance would you mind verifying it works for you? I appreciate your PR here, and I am hopeful that we can both maintain the existing signature-based authentication and support the new authentication method.

**Comment by frifri** [comment]
Thanks for this PR @drathm but I think I will be Closing it in favor of #30 if that's okay with you?

**Pull request closed without merging**
